name: Tweet Bot

on:
  schedule:
    - cron: "*/4 * * * *"  # Exécute toutes les 4minutes
  workflow_dispatch:  # Permet de lancer manuellement le workflow depuis l'interface GitHub

jobs:
  run-tweet-bot:
    runs-on: ubuntu-latest  # Utilise un environnement Ubuntu

    steps:
      - name: Checkout du dépôt
        uses: actions/checkout@v2

      - name: Installer Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Installe la dernière version de Python

      - name: Installer les dépendances
        run: |
          python -m pip install --upgrade pip
          pip install tweepy

      - name: Exécuter le bot
        run: python tweet_bot.py
        env:
          TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
          TWITTER_API_SECRET: ${{ secrets.TWITTER_API_SECRET }}
          TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_SECRET: ${{ secrets.TWITTER_ACCESS_SECRET }}
          TWITTER_BEARER_TOKEN: ${{ secrets.TWITTER_BEARER_TOKEN }}
